<?php

/*
* This is a PHP script that will perform simple batch metadata updates on a
* ContentDM instance.
*
* License: Copyright 2011 UC Regents. Open source BSD license.
* Author: Kevin S. Clarke <ksclarke@gmail.com>
*/

// Show me the errors!!
error_reporting(E_ALL);
ini_set('display_errors', '1');

require_once 'Zend/Http/Client.php';
require_once 'Zend/Config/Xml.php';
require_once 'Zend/Log/Writer/Stream.php';
require_once 'Zend/Log.php';
require_once 'Zend/Registry.php';
require_once 'Zend/Exception.php';

function reindex($http, $url) {
	$http->resetParameters(true);
	$http->setUri($url);
	$response = $http->request(Zend_Http_Client::GET);

	if (!($http->request(Zend_Http_Client::GET)->isSuccessful())) {
		throw new Exception("Reindexing failed!");
	}
	
	echo '<div>Reindexed: ' . $url . '</div>';
}

function startsWith($haystack, $needle) {
	$length = strlen($needle);
	return (substr($haystack, 0, $length) === $needle);
}

function update($http, $url, $data, $config) {
	$http->resetParameters(true);
	$http->setUri($url . $data[0]);
	$response = $http->request(Zend_Http_Client::GET);
	
	echo '<div>' . $url . $data[0] . ' ' . $data[1] . ' ' . $data[2] . '</div>';
	
	if ($response->isSuccessful()) {
		$doc = new DOMDocument();
		$doc->strictErrorChecking = FALSE;
		@$doc->loadHTML($response->getBody());
		$xml = simplexml_import_dom($doc);
		$forms = $xml->xpath('//form');
		$form_action = '/cgi-bin/admin/edititem.exe';
		$form = $xml->xpath('//form[@action="' . $form_action . '"]');

		$http->setUri('https://' . $config->webhost . $form_action);
		$http->resetParameters(true);
		$http->setAuth($config->user, $config->password);

		// Check that there is only one form and it's the one we want
		if (sizeof($forms) == 1 && sizeof($form) == 1) {
			foreach ($xml->xpath('//input') as $input) {
				$name = (string) $input->attributes()->name;
				$value = (string) $input->attributes()->value;

				// data[1] is field to be replaced; data[2] is the new value
				if (strcasecmp($name, $data[1]) == 0) {
					$http->setParameterPost($name, $data[2]);
				}
				else {
					$http->setParameterPost($name, $value);
				}
			}
			
			foreach ($xml->xpath('//textarea') as $textarea) {
				$name = (string) $textarea->attributes()->name;
				$value = (string) $textarea;
				
				// data[1] is field to be replaced; data[2] is the new value
				if (strcasecmp($name, $data[1]) == 0) {
					$http->setParameterPost($name, $data[2]);
				}
				else {
					$http->setParameterPost($name, $value);
				}
			}
			
			$response = $http->request(Zend_Http_Client::POST);
			if ($response->isSuccessful()) {
				echo "Success!";
			}
			else {
				echo new Exception('Update failed!');
			}
		}
		else {
			echo $xml->asXML();
			throw new Exception('Wrong number of forms on page');
		}
	
	}
	else {
		throw new Exception('Unable to read response');
	}
}

$config = new Zend_Config_Xml('config.xml', 'production');
$host = 'https://' . $config->webhost;
$url = $host . '/cgi-bin/admin/edittxt.exe?CISOROOT=%COL_ID%&CISOPTR=';
$reindex_params = 'CISOOP=index&CISOTYPE1=now&CISODB=';
$reindex_url = $host . '/cgi-bin/admin/putsched.exe?' . $reindex_params;
$collId = '';

$writer = new Zend_Log_Writer_Stream($config->logfile);
Zend_Registry::set('logger', new Zend_Log($writer));

try {
	if (isset($_POST['file']) || isset($_GET['file'])) {
		if (isset($_POST['file'])) {
			$batchfile = explode('.', $_POST['file']);
			$batchfile = explode('/', $batchfile[0]);
			$collId = '/' . $batchfile[1];
		}
		else {
			$batchfile = explode('.', $_GET['file']);
			$batchfile = explode('/', $batchfile[0]);
			$collId = '/' . $batchfile[1];
		}

		$reindex_url = $reindex_url . $collId;
		$url = str_replace('%COL_ID%', $collId, $url);
	}
	else {
		throw new Exception('No batch file specified');
	}
	
	$http = new Zend_Http_Client();
	$http->setCookieJar();
	$http->setAuth($config->user, $config->password);
	
	$file_handle = fopen('batch_files' . $collId . '.csv', "r");

	while (!feof($file_handle) ) {
		$data = fgetcsv($file_handle, 1024);

		// 3 in data count == (recId, fieldName, value)
		if (count($data) == 3) {
			update($http, $url, $data, $config);
		}
		else {
			// log
		}
	}
	
	fclose($file_handle);
	reindex($http, $reindex_url);
}
catch (Exception $details) {
	echo '<p>An error occurred (' . $details->getMessage() . ')</p>';
	echo '<p>' . $details->getTraceAsString() . '</p>';
}
	
?>

<!-- Generated by cdm-batch - https://github.com/ksclarke/cdm-batch -->
